In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib

In [2]:
import pandas as pd

In [3]:
PPI = pd.read_csv('orig_data/bio-decagon-ppi.csv',sep=',')
PF = pd.read_csv('orig_data/proteins.csv',sep=',')
DTI = pd.read_csv('orig_data/bio-decagon-targets-all.csv',sep=',')
DDI = pd.read_csv('orig_data/bio-decagon-combo.csv',sep=',')
DSE = pd.read_csv('orig_data/bio-decagon-mono.csv',sep=',')

In [8]:
print("Total number of PPI interactions:",len(PPI.index))
temp_prot = PPI[["Gene 1", "Gene 2"]].values.ravel()
print(len(temp_prot))
PPI_prot = pd.DataFrame(pd.unique(temp_prot),columns=['Gene'])
print("Total number of unique genes in PPI:",len(PPI_prot.index))

print(len(PF.index))
PF_prot = pd.DataFrame(pd.unique(PF["GeneID"].values),columns=['Gene'])
print("Total number of genes that have features:",len(PF_prot.index))

print("Total number of DTI interactions:",len(DTI.index))
DTI_prot = pd.DataFrame(pd.unique(DTI["Gene"].values),columns=['Gene'])
print("Total number of unique genes in DTI",len(DTI_prot.index))

Total number of PPI interactions: 715612
1431224
Total number of unique genes in PPI: 19081
5400
Total number of genes that have features: 5336
Total number of DTI interactions: 131034
Total number of unique genes in DTI 7795

In [10]:
pd.DataFrame(intersect1d(PPI_prot['Gene'],DTI_prot['Gene']))

              0
0             2
1             9
2            10
3            13
4            15
5            16
6            18
7            19
8            20
9            21
10           24
11           25
12           26
13           30
14           31
15           32
16           33
17           34
18           35
19           36
20           37
21           38
22           39
23           41
24           47
25           48
26           49
27           50
28           52
29           53
...         ...
7724  100287718
7725  100288332
7726  100288562
7727  100289087
7728  100289635
7729  100289678
7730  100293516
7731  100310846
7732  100423062
7733  100431172
7734  100505503
7735  100505591
7736  100506084
7737  100506164
7738  100506243
7739  100506742
7740  100507290
7741  100526693
7742  100526740
7743  100526835
7744  100526842
7745  100528030
7746  100529144
7747  100529240
7748  100529261
7749  100885850
7750  100996464
7751  100996642
7752  101059957
7753  101060200

[7754 rows x 1 columns]

In [ ]:
print("Total number of DTI interactions:",len(DTI.index))
DTI_prot = pd.DataFrame(pd.unique(DTI["Gene"].values),columns=['Gene'])
print("Total number of unique genes in DTI",len(DTI_prot.index))

In [ ]:
print(len(DTI.index))
DTI_drugs = pd.DataFrame(pd.unique(DTI["STITCH"].values),columns=['STITCH'])
print(len(DTI_drugs.index))
DTI_drugs.head()

In [ ]:
print(len(DDI.index))
temp_drugs = DDI[["STITCH 1", "STITCH 2"]].values.ravel()
print(len(temp_drugs))
DDI_drugs = pd.DataFrame(pd.unique(temp_drugs),columns=['STITCH'])
print(len(DDI_drugs.index))
DDI_drugs.head()

In [ ]:
print(len(DSE.index))
DSE_drugs = pd.DataFrame(pd.unique(DSE["STITCH"].values),columns=['STITCH'])
print(len(DSE_drugs.index))
DSE_drugs.head()

### Remove genes with no info about helices or strands and drop useless columns

In [ ]:
beta = df[df['n_strands'].str.contains('evidence',na=False)]
print(len(beta.index))
df = beta[beta['n_helix'].str.contains('evidence',na=False)]
print(len(df.index))
df.head()

### Split Helix and Strand columns

In [ ]:
beta = pd.DataFrame(df.n_strands)
beta = beta['n_strands'].str.split("STRAND", expand = True)
beta.head()

In [ ]:
alpha = pd.DataFrame(df.n_helix)
alpha = alpha['n_helix'].str.split("HELIX", expand = True)
alpha.head()

### Reeplace columns for the number of elements in the column

In [ ]:
df.loc[:,'n_strands'] = beta.count(axis=1)
df.loc[:,'n_helix'] = alpha.count(axis=1)
df.head()

In [ ]:
df.to_csv('proteins.csv',index=False)